version: '3'
services:
  ki-finance:
    build: .
    image: 'kifin_image'
    container_name: 'kifin_container'
    working_dir: '/work'
    tty: true
    stdin_open: true
    volumes:
      - $PWD:/work